### ISSUE TITLE
Release 3.2.0 fails when parsing annotations

### ISSUE THREAD

**Issue by xabbuh** [phpDocumentor/ReflectionDocBlock#108]
With the release of 3.2.0 (more specific the changes from #89) parsing a docblock fails if it not contains only phpdoc but also annotations (for example, to configure Doctrine mapping metadata). 

For example, in Symfony we have the following test data:

```php
class Dummy extends ParentDummy
{

    /**
     * @var \DateTime[]
     * @Groups({"a", "b"})
     */
    public $collection;

    // ...
}
```

I am not sure what could be a possible fix here. Silently ignore these lines? But this may be bad user experience as it does not help to find your own mistakes. Maybe ignore only tags that are followed by parentheses?

**Comment by mpajunen** [comment]
I can confirm this, we ran into the same issue. Ignoring tags followed by parenthesis as @xabbuh suggested is probably a good enough solution.

**Comment by esynaps** [comment]
See PR #107

**Comment by frenchcomp** [comment]
I confirm the same issue, since the commit 248e5 ( https://github.com/phpDocumentor/ReflectionDocBlock/commit/248e5f69dcdee599dffc2d13aa566a14010fbe36 )
The regex works with the old pattern (/^@([\w\-\_\\]+)(?:\s*([^\s].*)|$)?/us) but not with the new pattern /^@([\w\-\_\\]+)(?:\s+([^\s].*)|$)/us
