### ISSUE TITLE
Notice:  Uninitialized string offset: 0 in version 3.2.1

### ISSUE THREAD

**Issue by forgie1** [phpDocumentor/ReflectionDocBlock#111]
I'm getting cca 50% of times the same code is run here https://github.com/phpDocumentor/ReflectionDocBlock/commit/183824db76118b9dddffc7e522b91fa175f75119#commitcomment-23494690 Notice: `Uninitialized string offset: 0`.

`$this->tagFactory->create(trim($tagLine), $context);` was called with arguments:

```
$tagLine = "@ORM\Entity" (11)
$context = phpDocumentor\Reflection\Types\Context #01 
                    namespace private => "Plugins\Doctrine\Products" namespaceAliases private => array (2) 
                           ORM => "Doctrine\ORM\Mapping" 
                           Entities => "Etten\Doctrine\Entities"
```

in phpDocumentor\Reflection\DocBlockFactory:231 , resulting in the notice.

**Comment by ahilles107** [comment]
I have this same error but in other place: 
```
notice: Uninitialized string offset: 0 in
      vendor/phpdocumentor/reflection-docblock/src/DocBlock/StandardTagFactory.php
      line 116
```

**Comment by forgie1** [comment]
@ahilles107 yes, that is the same line I'm getting this error: https://github.com/phpDocumentor/ReflectionDocBlock/commit/183824db76118b9dddffc7e522b91fa175f75119#commitcomment-23494690

**Comment by esynaps** [comment]
Same here, i'm adding "()" to all tags => it works

^@([\w\-\_\\\\]+)(?:\s*([^\s].*)|$)

@JMS\Exclude => 
Full match | 0-12 | `@JMS\Exclude`
Group 1. | 1-12 | `JMS\Exclude`

@JMS\Exclude()
Full match | 0-14 | `@JMS\Exclude()`
Group 1. | 1-12 | `JMS\Exclude`
Group 2. | 12-14 | `()`

**Comment by temp** [comment]
This is definitely a BC break. 
This was introduced in StandardTagFactory.php, the check for $tagBody[0] being "[", but with no Annotations parameters (and no brackets) this value is an empty string, meaning that index 0 of the string is not set.
[Compare 3.2.0 to 3.2.1](https://github.com/phpDocumentor/ReflectionDocBlock/compare/3.2.0...3.2.1)
This can be easily fixed by checking for the value not being empty:
```php
if (!empty($tagBody[0]) && $tagBody[0] === '[') {
```

**Comment by jaapio** [comment]
Fixed in 3.2.2 and 4.0.1. Please let me no if you have any issues with the new releases

**Comment by keradus** [comment]
Works like a charm now, thanks ;)

**Comment by GrahamCampbell** [comment]
Excelent. 👍
