### ISSUE TITLE
deprecated tag couses error in version 3.2.1 

### ISSUE THREAD

**Issue by mieszkomalawski** [phpDocumentor/ReflectionDocBlock#114]
Problem with @deprecated tag in \phpDocumentor\Reflection\DocBlock\StandardTagFactory::create

Uninitialized string offset: 0

here: 

` if ($tagBody[0] === '[') {
            throw new \InvalidArgumentException(
                'The tag "' . $tagLine . '" does not seem to be wellformed, please check it for errors'
            );
        }`

This is because @deprecated tag does not require description

**Comment by jaapio** [comment]
please update to 3.2.2 which was released this week. Fixed by #111
