### ISSUE TITLE
Don't discard entire DocBlock on malformed tag

### ISSUE THREAD

**Issue by BasKooij** [phpDocumentor/ReflectionDocBlock#123]
I'm using Swagger annotations in the PHP doc blocks to generate a Json Swagger Api specification. In addition to the normal PhpDocumentor tags. A block might look like this:

/**
     * @var string
     * @SWG\Property(
     *     type="string"
     * )
     */
    public $myProperty

Now the call stack for parsing this this might look something like this:

PhpDocExtractor::getDocBlock()  -> try catch per doc block, silently insert null on failure
DocBlockFactory::create()
DocBlockFactory::parseTagBlock() -> Loop through lines in doc block
StandardTagFactory::create()
StandardTagFactory::extractTagParts() -> throw InvalidArgumentException(not well formed)

Since the line @SWG\Property( cannot be parsed, an exception is thrown at this point. This causes the entire doc block to be discarded, despite the fact that the first line in the block has been parsed successfully. This could be solved by moving the try/catch to line 231 in DocBlockFactory::parseTagBlock(). This would let the recognized and well formed tags be parsed and leave out the unsupported ones, instead of silently ignoring the entire block when an unsopprted syntax is encountered.

I wasn't able to easily fix this since the classes are marked final so I can't extend the class. Besides, the code that would have to be modified is in a private method. Which also eliminates the option of creating an adapter for the class.

**Comment by jaapio** [comment]
I was not able to reproduce this issue. Please have a look at the testcase I wrote for this usecase.
https://github.com/phpDocumentor/ReflectionDocBlock/blob/master/tests/integration/DocblocksWithAnnotationsTest.php

Feel free to reopen the issue when needed
