### ISSUE TITLE
Help: Fully Qualified Namespace

### ISSUE THREAD

**Issue by mpoiriert** [phpDocumentor/ReflectionDocBlock#158]
I am using this library in a swagger library I have built (https://github.com/mpoiriert/swagger)
Instead of all the swagger library out there I am trying to reduce the maximum of information from what is already there. So base on multiple extractor I am extracting the information and some of it comes from the PHP Doc. For that I am using your library.

This is integrated in Symfony and Currently doing some work for Laravel (4.2)

Here is a example of minimalist controller that I would have

```
namespace Demo;

use Demo\DTO\Class1;

class TestController
    /**
     * @Route(path="/test", methods={"post"})
     *
     * @Swagger\Tag("Demo")
     *
     * @return Class1 The description of the return value
     */
    public function testAction()
    {
        return new Class1();
    }
```
You can see how I use your library in the class: https://github.com/mpoiriert/swagger/blob/master/Extraction/Extractor/PhpDocOperationExtractor.php

Problem I have is that it will consider the return class "Class1" and not " Demo\DTO\Class1".

There is probably something I should initialise first to make this work, it would be great to pin point out to me :) 

I am using version >=3.0 so I would like/need a solution that work for all versions if possible.

**Comment by jaapio** [comment]
Hi,
The create method of the factory accepts more arguments than just the comment. It accepts the context of our typeresolver. Please have a look at the readme of that component to see how to create a context.

**Comment by mpoiriert** [comment]
I think I am good

```
$contextFactory = new ContextFactory();
$context = $contextFactory->createFromReflector($reflector);

$docComment = DocBlockFactory::createInstance()->create($reflector->getDocComment(), $context);
/* etc */
```
From there everything seems with the fully qualified namespace.

Thanks !
