### ISSUE TITLE
Fails with multiple grouped use statements

### ISSUE THREAD

**Issue by natebrunette** [phpDocumentor/ReflectionDocBlock#159]
When parsing multiple classes defined in a group, only the first class keeps the fully qualified namespace.

```php
use My\Namespace\{Foo, Bar};
```

Will result in `My\Namespace\Foo` and `Bar`

**Comment by ragboyjr** [comment]
Just lost an hour of my life discovering this bug as well.

**Comment by ragboyjr** [comment]
https://github.com/phpDocumentor/TypeResolver/pull/64

**Comment by ashnazg** [comment]
If this is fixed in TypeResolver, might just need a dep version bump... should also add a specific test case here in ReflectionDocBlock though.

**Comment by jaapio** [comment]
This is fixed in typeresolver. We can do a composer require update to reset the minimal required version.
0.7.0

**Comment by ashnazg** [comment]
Yep... I would still like to get a new testcase in here specifically for this scenario too.
