### ISSUE TITLE
Exception in StandardTagFactory

### ISSUE THREAD

**Issue by ancpru** [phpDocumentor/ReflectionDocBlock#165]
When a tag body starts with a "[", an exception is raised:
```
   public function create(string $tagLine, ?TypeContext $context = null): ?Tag
    {
        if (! $context) {
            $context = new TypeContext('');
        }

        [$tagName, $tagBody] = $this->extractTagParts($tagLine);

        if ($tagBody !== '' && $tagBody[0] === '[') {
            throw new \InvalidArgumentException(
                'The tag "' . $tagLine . '" does not seem to be wellformed, please check it for errors'
            );
        }

        return $this->createTag($tagBody, $tagName, $context);
    }
```

Is there a reason for that?

We try to use some kind of markdown syntax in our project and the parser failes on a tag like "@see [xxx](yyy)"

Is there a description somewhere where to hook in to do some pre-processing? In the new version many things are declared final and it looks quite difficult to extend (or I just have not found the right place to hook in).

**Comment by jaapio** [comment]
I added that check because a `[` as first character in a tag body seems to be invalid. I don't remember any more in which context this was the case. But it was something with annotations. The tag body doesn't have any relation with the error you are describing in `@see xxx`.

Please provide an example of the situation the parsing fails. So we can investigate what is going on

**Comment by ancpru** [comment]
> I added that check because a `[` as first character in a tag body seems to be invalid. I don't remember any more in which context this was the case. But it was something with annotations. The tag body doesn't have any relation with the error you are describing in `@see xxx`.
> 
> Please provide an example of the situation the parsing fails. So we can investigate what is going on

Well, I am at work to port the yii2-apidoc to the new reflection version. apidoc uses markdown and the yii-source contains tags like 

@see [\This\Is\My\Class] or 
@see [theOtherMethod()]

Thus factory gets a string starting with "[" 

It might make sense to change the format in the yii source as the @see syntax is now defined as "@see [URI | FQSEN] [<description>]", but I try to stay compatible with existing source.
