### ISSUE TITLE
@method Invalid method name with no arguments

### ISSUE THREAD

**Issue by Ne-Lexa** [phpDocumentor/ReflectionDocBlock#174]
Problem phpDoc:
```php
/**
 * @method static CategoryEnum GAME() Returns the category id 'Games'.
 */
```
Result:
```php
phpDocumentor\Reflection\DocBlock\Tags\Method^ {#134
      #name: "method"
      -methodName: "Returns"
      -arguments: []
      -isStatic: true
      -returnType: phpDocumentor\Reflection\Types\Object_^ {#141
          -fqsen: phpDocumentor\Reflection\Fqsen^ {#136
              -fqsen: "\CategoryEnum"
              -name: "CategoryEnum"
          }
      }
      #description: phpDocumentor\Reflection\DocBlock\Description^ {#135
          -bodyTemplate: "the category id 'Games'."
          -tags: []
      }
}
```
The name of the method is '**Returns**', and should be '**GAME**'.

But, If you specify the arguments or remove `()`, it will work correctly.
```php
/**
 * @method static CategoryEnum GAME Returns the category id 'Games'.
 * @method static CategoryEnum FAMILY(int $foo) Returns the category id 'Family'.
 */
```
Result:
```
[
    0 => phpDocumentor\Reflection\DocBlock\Tags\Method^ {#134
      -methodName: "GAME"
      -arguments: []
      #description: phpDocumentor\Reflection\DocBlock\Description^ {#135
        -bodyTemplate: "Returns the category id 'Games'."
      }
    }
    1 => phpDocumentor\Reflection\DocBlock\Tags\Method^ {#128
      -methodName: "FAMILY"
      -arguments: array:1 [
        0 => array:2 [
          "name" => "foo"
          "type" => phpDocumentor\Reflection\Types\Integer^ {#130}
        ]
      ]
      #description: phpDocumentor\Reflection\DocBlock\Description^ {#131
        -bodyTemplate: "Returns the category id 'Family'."
      }
    }
]
```

I consider this behavior to be incorrect, since the "methodName()" is used everywhere in the documentation.

The code uses this regular expression: https://regex101.com/r/VEOvgm/2

**Comment by othercorey** [comment]
I am running into this issue trying to parse cakephp 4.0 annotations. We have the same type of method names with `methodName()`.

This is with 5.*@alpha.

**Comment by jaapio** [comment]
I think you are both right. We should fix this. But I don't want to break the original behavior. 
PR's are welcome, and will be reviewed very fast since we are currently back to speed with the development of a new phpdocumentor version.

**Comment by othercorey** [comment]
@jaapio I will work on a PR.  I was just about to fork so we could have working docs with cake!

**Comment by othercorey** [comment]
@jaapio What is the best way to test locally? The unit tests seem very custom to github actions.

**Comment by othercorey** [comment]
@jaapio PR is up.

**Comment by jaapio** [comment]
Thanks to @othercorey this issue has been fixed.
