### ISSUE TITLE
Immutability of Docblocks 

### ISSUE THREAD

**Issue by atymic** [phpDocumentor/ReflectionDocBlock#175]
Hi,

I was a bit confused by this library. I was intending to use it to modify some existing docblocks, but it seems that it's (kind of) immutable?

Is there a reason why the `removeTag` method is public (and mutates the Docblock) and the `addTag` method is private?

Thanks!

**Comment by mvriel** [comment]
Hello @atymic, 

this library is meant to parse and interpret docblocks but indeed not intended to modify them or write them back to disk.

Which use case are you trying to serve? I am interested to hear more on why you are asking this question :)

**Comment by atymic** [comment]
I was looking around for a library to read and manipulate docblocks, so I looked in `laravel-ide-helper` package since it does a lot of docblock generation.
It seem that they use a fork of this package, with an `appendTag` method added
https://github.com/barryvdh/ReflectionDocBlock/blob/master/src/Barryvdh/Reflection/DocBlock.php#L425-L440

I'm using it to update docblocks on a model in laravel pragmatically.

For the moment, i've worked around it by creating a new docblock instance, which is constructed with `array_merge($existing->getTags(), $newTags)` which seems to work ok.

I'd be happy to create a PR with tests if you have something that you would be happy with.

**Comment by atymic** [comment]
It's a bit strange atm, as the `removeTag` method is the only method that allows mutation 🤔

**Comment by atymic** [comment]
It seems it was added by https://github.com/phpDocumentor/ReflectionDocBlock/issues/124 for similar purposes (changing existing docblocks)

**Comment by jaapio** [comment]
I think that was more or less my failure that I merged that one.  Like @mvriel states this library is intended to be a reflection of the actual docblock. 

The project you are referencing is old, and wouldn't even work with the newer versions of phpdocumentors docblock class. 

I think your approach to create a new docblock with the getters of the old one is the correct way of using this library to mutate docblocks. From our point of view there is no need to mutate docblocks. And if you ask me there are way better libraries to mutate code. Which do even allow you to fix the indentation. For example: https://docs.zendframework.com/zend-code/generator/examples/

**Comment by atymic** [comment]
Thanks for the suggestion, that's a much better package!
Have switched over to that.

Maybe worth removing the `removeTag` method in the next major version, will close this issue now though :)

Thanks for your help.
