### ISSUE TITLE
Expected an implementation of StaticMethod for Example

### ISSUE THREAD

**Issue by runphp** [phpDocumentor/ReflectionDocBlock#181]
Expected an implementation of \"phpDocumentor\\Reflection\\DocBlock\\Tags\\Factory\\StaticMethod\". Got: \"phpDocumentor\\Reflection\\DocBlock\\Tags\\Example\"

**Comment by mvriel** [comment]
Thank you for your bug report; I have fixed this bug on master and release-4.x. We will shortly push a new tag for release-4.x
