### ISSUE TITLE
array_walk_recursive() expects parameter 1 to be array, null given

### ISSUE THREAD

**Issue by nixilla** [phpDocumentor/ReflectionDocBlock#215]
In [PHP 7.4](https://www.php.net/manual/en/migration74.other-changes.php) there is a new optimisation setting called _zend.exception_ignore_args_ which is on by default on some systems.

When it's on, it excludes ```$trace['args']``` index from array returned from function```Throwable::getTrace()``` and therefore the above error occurs.

This has been already fixed in this commit: e8384e4 so all you need to do is to create a new release, please.

**Comment by jaapio** [comment]
Release 5.1.0 has been created.
