### ISSUE TITLE
ReflectionParameter::getClass() is deprecated on PHP 8

### ISSUE THREAD

**Issue by ondrejmirtes** [phpDocumentor/ReflectionDocBlock#241]
From the [UPGRADING guide in php-src](https://github.com/php/php-src/blob/master/UPGRADING):

```
  . ReflectionParameter::getClass(), ReflectionParameter::isArray(), and
    ReflectionParameter::isCallable() are deprecated.
    ReflectionParameter::getType() and the ReflectionType APIs should be used
    instead.
```

This is called in StandardTagFactory: https://github.com/phpDocumentor/ReflectionDocBlock/blob/41f77e86971e4abaca59b1c7de22cd04ac1bce27/src/DocBlock/StandardTagFactory.php#L257

**Comment by jaapio** [comment]
There is a pr for this :+1: 

https://github.com/phpDocumentor/ReflectionDocBlock/pull/240

**Comment by jaapio** [comment]
This should be done now. Please try 5.2.0 let us know when you have any issues regarding php 8 support.
