### ISSUE TITLE
Push master version as new tag

### ISSUE THREAD

**Issue by Glancu** [phpDocumentor/ReflectionDocBlock#245]
I need master version with tag like 5.1.1. I need this for https://github.com/phpspec/prophecy/issues/491

**Comment by GrahamCampbell** [comment]
The next version will be 5.2.0, not 5.1.1, and I don't think it's quite ready yet?

**Comment by jaapio** [comment]
Still need to address the warnings in the unittests. If anyone has time to fix those PR's are very welcome.

**Comment by jaapio** [comment]
Tag has been created.
I was able to run the unittest local on php 8, but with some tricks. github actions refuses to run phpunit because of some issue that was already solved. And will be part of phpunit 9.3.
