### ISSUE TITLE
PHP 8.0 Broken Relative Types

### ISSUE THREAD

**Issue by GrahamCampbell** [phpDocumentor/ReflectionDocBlock#248]
Resolving relative types in phpdoc was broken recently, presumably due to https://github.com/php/php-src/commit/7a3dcc3e339cde2177ba4fe8fc45f78c94dfbb29.

**Comment by GrahamCampbell** [comment]
It also looks like the current test suite crashes on PHP 8.0:

```
PHPUnit 9.3-dev by Sebastian Bergmann and contributors.

Runtime:       PHP 8.0.0-dev
Configuration: /data/phpunit.xml.dist
Warning:       No code coverage driver available

  Warning - The configuration file did not pass validation!
  The following problems have been detected:

  Line 20:
  - Element 'filter': This element is not expected.

  Test results may not be as expected.

...

Test 'phpDocumentor\Reflection\DocBlockFactoryTest::testCreateDocBlockFromReflection' started
PHP Fatal error:  Type mixed cannot be marked as nullable since mixed already includes null in /data/vendor/mockery/mockery/library/Mockery/Loader/EvalLoader.php(34) : eval()'d code on line 1198
```

**Comment by GrahamCampbell** [comment]
> It also looks like the current test suite crashes on PHP 8.0:

This is actually a known bug in Mockery, a noted down in https://github.com/mockery/mockery/issues/1083.

**Comment by GrahamCampbell** [comment]
I have fixed the issue with Mockery now. If you update the lock file, the tests should run on PHP 8 again.

**Comment by jaapio** [comment]
Just updated mockery, let's see what happens.

**Comment by xabbuh** [comment]
see phpDocumentor/TypeResolver#114
