### ISSUE TITLE
PHP 8.0 Deprecations

### ISSUE THREAD

**Issue by leemcd56** [phpDocumentor/ReflectionDocBlock#264]
In **StandardTagFactory.php**, the following methods are [deprecated in PHP 8.0](https://php.watch/versions/8.0/deprecated-reflectionparameter-methods):

- `ReflectionParameter::getClass()`
- `ReflectionParameter::isArray()`
- `ReflectionParameter::isCallable()`

**Comment by jaapio** [comment]
I think you need to update the version of this lib you are using.  v5 doesn't use these methods anymore

**Comment by leemcd56** [comment]
Ah, sorry about that! I ended up here following the dependency trail of the PHP Intellisense plugin in VS Code, but it appears to be using a few outdated dependencies... 😅
