### ISSUE TITLE
Method with array-values as default parameter ends in invalid tag

### ISSUE THREAD

**Issue by TiMESPLiNTER** [phpDocumentor/ReflectionDocBlock#273]
I'm not sure if it's a bug or maybe the notation is not allowed. But this example here:

```
/**
 * @method mixed randomElement(array $array = array('a', 'b', 'c'))
 */
class Generator
{

}
```

ends up in an invalid tag with the message:

> "\'b'" is not a valid Fqsen.

**Comment by TiMESPLiNTER** [comment]
Might be related to #271

**Comment by jaapio** [comment]
this is indeed releated to #271, closing this in favor of that issue. 
Looking into it right now.
