### ISSUE TITLE
MethodTag::getArguments 

### ISSUE THREAD

**Issue by armetiz** [phpDocumentor/ReflectionDocBlock#29]
This function return an array of array, there is no defined order of this structure.

I guess it could be useful to add a correct interpretation of this information : [[type] [parameter]<, ...>]

There is 3 informations : 
- name
- type
- default value

**Comment by johannesschobel** [comment]
It would be awesome if we could access the various information of a tag! Any implementation available?

**Comment by jaapio** [comment]
The mentioned reflection classes are part of phpdocumentor/reflection. I can imagine that we could create a param like class to support typed arguments. But before going that way I want to have a good benchmark setup avaliable. So we can measure the impact of changes like this.

I'm sure that we will get the same request for callables. And other complex docblock tags. Main concern is the memory usage in applications like phpdocumentor.

**Comment by ashnazg** [comment]
Right, but Reflection depends on ReflectionDocBlock, not the other way around.  If the whole paradigm in ReflectionDocBlock is "return strings for all the info you ask for", I'd say it should stay that way *in this library*.  Maybe the Reflection library itself could be the level of providing higher level classes wrapped around these strings.

**Comment by jaapio** [comment]
I started an effort to get this thing done #304
