### ISSUE TITLE
[SUGGESTION] DocBlockFactory::create - auto-create Context if passed $docblock is Reflector

### ISSUE THREAD

**Issue by Amegatron** [phpDocumentor/ReflectionDocBlock#297]
In my personal experience, every time I call `DocBlockFactory::create` passing a ReflectionProperty, I need to manually pass a Context, created by `ContextFactory::createFromReflector($property)`. So, I suppose this behavior could be done by default in `DocBlockFactory::create` itself: each time a `$docblock` is a Reflector, according context could be automatically created inside this method. Instead, it just creates an "empty" Context.

Context is needed for properties (or any other Reflections), where tags have short-references to imported classes in tags. Most often these are `@var`'s like `@var SomeClass[] $argument`, or `@var Collection<SomeClass> $argument`. If this suggestion if OK, I could make a PR.

**Comment by jaapio** [comment]
Hi,

Thanks for sharing this. My opinion on this is that I don't want to connect these factories in the library. I understand your use-case. and for many people using the library this might work. However it has a massive performance impact. Creating the context is rather slow. So I would not recommend you to do this every time you need to parse a docblock above a property. It might be better to wrap this whole thing into a helper class that stores some cache based on classname for example, to speed up your process. 

The speed of creating a context is depending on the size of your source files.

**Comment by Amegatron** [comment]
Thanks for the reply, sounds reasonable. In this case having a separate wrapper with cache would be a wise decision.

**Comment by jaapio** [comment]
I will close this issue, since there is nothing todo in this project to create such wrapper. This is more an integration thing. 

Thanks for reaching out to us.
