### ISSUE TITLE
Deprecated messages with PHP 8.2 because of non up-to-date dependencies

### ISSUE THREAD

**Issue by niconoe-** [phpDocumentor/ReflectionDocBlock#347]
Hi! :slightly_smiling_face: 

Using the version 5.3.0 of ReflectionDocBlock, usage of webmozart/assert dependency with PHP 8.2 is producing a deprecated message `Deprecated: Use of "static" in callables is deprecated in …`.

This is fixed on `webmozart/assert` in version 1.11.0 but as ReflectionDocBlock 5.3.0 relies on `webmozart/assert:v1.10.0`, the fix is not replicated into the latest version of this project. This causes for instance PHP Infection which relies on the latest released tag of ReflectionDocBlock to produce this deprecated messsage.

As your `master` seems to already be aligned with `webmozart/assert:v1.11.0`, would it be possible to just release a patch version "5.3.1" so that external projects (like PHP Infection) can rely on it and get rid of this deprecated message?

It looks like unit tests and all checks are already done (otherwise, you wouldn't allow a PR merged in `master`), so only a tag release would help here.

Thanks a lot.

**Comment by andrew-demb** [comment]
Hi.
Package allows installing any v1 version after v1.9.1

https://github.com/phpDocumentor/ReflectionDocBlock/blob/566af9fb94c556de91562fcfcbc392f66680111b/composer.json#L19

You can update this dependency in your project in any way

**Comment by niconoe-** [comment]
I could ask PHP Infection to add a new dependency toward "webmozart/assert:^1.11.0" so that even if they rely on ReflectionDocBlock 5.3.0, this will no conflict, you're right.

Nevertheless, the problem here is that PHP Infection is not directly calling any class of webmozart/assert package. Each time the runtime goes to this package, it's from ReflectionDocBlock, so they're actually not directly requiring webmozart/assert. It's just a dependency of a dependency because ReflectionDocBlock is using it.   
By asking PHP Infection to explicitly rely on webmozart/assert, I will ask them to create a dependency that will become a ghost dependency when ReflectionDocBlock will stop using it, and for that reason, I'm pretty sure they'll refuse.
