### ISSUE TITLE
Literal strings/ints causes classes not to be FQCNed

### ISSUE THREAD

**Issue by kkmuffme** [phpDocumentor/ReflectionDocBlock#348]
Given this:

```
/**
 * @param 'GET'|SomeClass $arg
 */
```

where the context correctly contains the SomeClass FQCN (Foo\SomeClass), it will not correctly create this:

```
$docblock = $docBlockFactory->create($comment, $context);
```

Nothing is thrown/no error, but the output is identical to the input, even though it should be:

```
/**
 * @param 'GET'|Foo\SomeClass $arg
 */
```

When removing the literal string, it works correctly.
The same issue also happens when using literal ints (e.g 9|SomeClass)

**Comment by jaapio** [comment]
I added a testcase to ensure the correct behavior. This will be solved in a next release.
