### ISSUE TITLE
Change Tag class hierarchy

### ISSUE THREAD

**Issue by aik099** [phpDocumentor/ReflectionDocBlock#36]
Here is current hierarchy:
![phpdocumentordocblock_tagclasses](https://cloud.githubusercontent.com/assets/1277526/3637862/60795eb6-1025-11e4-9872-3bfb94c47540.png)

Because of it we use `instanceof` operator to check for `ParamTag` the `PropertyTag` will also match.

The problem lies in fact, that you extend tag classes one from another because they obviously share something. Instead you should have several base abstract classes and extend relevant classes from them. This way people who want to match group of classes will match on abstract class, but who want to check for a specific class can do that easily as well.

**Comment by mvriel** [comment]
I am currently working on version 3 of this component and this won't have this hierarchy
