### ISSUE TITLE
Undefined array key 2

### ISSUE THREAD

**Issue by GalileoWebagentur** [phpDocumentor/ReflectionDocBlock#384]
https://github.com/phpDocumentor/ReflectionDocBlock/commit/2911a4807ed2a22178ea7c0149c3bfdd62558cb5#diff-b202007d4d220f51247c8acc26a042f9e0dd25cd7c79d85fc5cc6b3e1aecc682

This file change is killing the tokenizing of some third party libraries we have installed with a "undefined array key 2" error.

Examples:
https://github.com/FluidTYPO3/vhs/blob/development/Classes/ViewHelpers/Media/ExistsViewHelper.php#L32
https://github.com/FluidTYPO3/vhs/blob/development/Classes/ViewHelpers/Extension/LoadedViewHelper.php#L50

Backported it to 5.4.1 in several projects until this is fixed.

**Comment by jaapio** [comment]
Thanks for reporting!
