### ISSUE TITLE
Too few arguments to function PHPStan\PhpDocParser\Lexer\Lexer::__construct(), 0 passed

### ISSUE THREAD

**Issue by alexinteam** [phpDocumentor/ReflectionDocBlock#390]
Hello, having an wth symfony serilalizer
using `symfony/serializer@v6.4.13` and `"phpdocumentor/reflection-docblock": "5.6.0"` (newest for now).
when creating new Serializer object
```
$this->serializer = new Serializer([
            new ObjectNormalizer(null, null, null, new PhpDocExtractor(), null),
            new GetSetMethodNormalizer(),
            new ArrayDenormalizer()
        ], ['json' => new JsonEncoder()]);
```
getting error
`ArgumentCountError: Too few arguments to function PHPStan\PhpDocParser\Lexer\Lexer::__construct(), 0 passed in /vendor/symfony/type-info/TypeResolver/StringTypeResolver.php on line 66 and exactly 1 expected`

**Comment by jaapio** [comment]
This is an upstream issue, please read: https://github.com/symfony/symfony/pull/58800
