### ISSUE TITLE
Adding support of phpstan/phpdoc-parser ^2.0 is a breaking change

### ISSUE THREAD

**Issue by patrickbroens** [phpDocumentor/ReflectionDocBlock#391]
In v5.6.0 support for `phpstan/phpdoc-parser` version 2.0 has been added. This change should have triggered a new major version, 6.0.0, instead of a new minor version.

The reason for this is the object `PHPStan\PhpDocParser\Lexer\Lexer` has changed, including the constructor parameters. In version 1 the constructor parameter expects a boolean, but in version 2 NOT a boolean is expected, but the object `PHPStan\PhpDocParser\ParserConfig`, which is a breaking change.

The Lexer is constructed in `phpDocumentor\Reflection\DocBlock\Tags\Factory\AbstractPHPStanFactory on line 47`, where the parameter is still a boolean and not the expected object. 

Please remove the `phpstan/phpdoc-parser` version 2.0 support from the version 5 and start working on a new major version 6, because a lot is breaking currently.

**Comment by jaapio** [comment]
This is an upstream issue, please read: https://github.com/symfony/symfony/pull/58800

I will not provide a fix as this is not a breaking change.

**Comment by patrickbroens** [comment]
Still in `phpDocumentor\Reflection\DocBlock\Tags\Factory\AbstractPHPStanFactory` the same problem exists as in `symfony/symfony` and should be fixed there the way they did it in Symfony, otherwise the `Lexer` is still constructed the wrong way. I understand when resolving this issue no new major is needed

**Comment by jaapio** [comment]
I think we already did that, https://github.com/phpDocumentor/ReflectionDocBlock/blob/5.x/src/DocBlock/Tags/Factory/AbstractPHPStanFactory.php#L49

**Comment by patrickbroens** [comment]
Oops, sorry Jaap, you're right. My mistake. I was looking in an older version.
