### ISSUE TITLE
Multiline @param description duplicating last line

### ISSUE THREAD

**Issue by Furgas** [phpDocumentor/ReflectionDocBlock#393]
Test class/method/param:
```php
class Foo {

	/**
	 * @param int $baz Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas varius, tellus in cursus
	 *     dictum, justo odio sagittis velit, id iaculis mi dui id nisi.
	 */
	public function bar(int $baz): void {

	}
}
```

Result of `getDescription()` on `@param` tag:
```
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas varius, tellus in cursus
dictum, justo odio sagittis velit, id iaculis mi dui id nisi.
dictum, justo odio sagittis velit, id iaculis mi dui id nisi.
```

I've prepared a [repository](https://github.com/Furgas/phpdocumentor-reflection-test) with this test case.

The direct cause for this is in `ParamFactory::create()` method (with my comments):
```php
// value in "description" attribute is wrong (with duplicated line)
$description = $tagValue->getAttribute('description');
if (is_string($description) === false) {
    // this value is valid (without duplicated line), but is shadowed be the attribute
    $description = $tagValue->description;
}
```

I don't know why there is additional "description" attribute with invalid value and is preferred over "description" property, but I guess the source of this problem is in `PhpDocParser::parseText()` method.

**Comment by johnbillion** [comment]
I'm seeing this too. The issue was introduced in 5.6.0. Version 5.5.1 is fine.

**Comment by jaapio** [comment]
Thanks for the report and detailed testcase. I found that this is related to a work around we implemented to fix a bug in an upstream library.
