### ISSUE TITLE
Period ends short description even if it is not at the end of the line

### ISSUE THREAD

**Issue by xelan** [phpDocumentor/ReflectionDocBlock#63]
**Example Code:**

``` php
<?php
$docblock = <<<DOCBLOCK
/**
 * This is a short (...) description.
 *
 * This is a long description.
 *
 * @return void
 */
DOCBLOCK;

$phpdoc = new \phpDocumentor\Reflection\DocBlock($docblock);
echo $phpdoc->getShortDescription() . PHP_EOL;
```

**Expected output:**
`This is a short (...) description.`

**Actual output:**
`This is a short (.`

**Tested version:**
`phpdocumentor/reflection-docblock 2.0.4`

Issue #34 seems to be related to this. Thank you very much!

**Comment by cebe** [comment]
Here is some code I once wrote to avoid stopping at abbreviations: https://github.com/yiisoft/yii/commit/9f3170680a1f11c75d77f16da4d3c220ef834710#diff-7e0761c082ba85f043ca7e92bea9b71eR481
a similar case, but does not cover this issue.

**Comment by cebe** [comment]
May be solved by a regex like this: https://regex101.com/r/wI1aV5/1 `^(.+?($|\w\w\.(?!(\.|\w\.))))`.
Would be good to have a larger set of test cases for this.

**Comment by jaapio** [comment]
I need some help on this issue. In v3 we have multiple testcases that are showing that we support a very wide range of combinations only the summary with multiple dots is not working like expected.
