### ISSUE TITLE
How to retrieve Tag values?

### ISSUE THREAD

**Issue by chrismervyn** [phpDocumentor/ReflectionDocBlock#64]
I want to retrieve the name and value for tags in a docblock.

```
$phpdoc = <<<Docblock
/**
     * This function Describes any given method. 
     * @param string $methodName Tag method name to describe.
     * @return bool true/false
     */
Docblock;

$parsed = new \phpDocumentor\Reflection\DocBlock($phpdoc);
$desc =     $phpdoc->getShortDescription(); 
```

I have got this far. Now, how do I retrieve the values for `@param` & `@return`?

**Comment by cebe** [comment]
`$tags = $parsed->getTags();`

this will give you an array of elements of type [Tag](https://github.com/phpDocumentor/ReflectionDocBlock/blob/master/src/DocBlock/Tag.php).

**Comment by chrismervyn** [comment]
It gives me an array alright, but that `array` is basically a `__tostring` representation of the `$parsed` object. And thus the values are `protected object properties`. Is there are cleaner way to retrieve the values?

**Comment by johannesschobel** [comment]
Is there a way to get the values ```bool``` and ```true/false``` when looping through the tags?

**Comment by kelunik** [comment]
Sure.

```php
if ($docBlock->hasTag("return")) {
    /** @var Return_[] $returnTags */
    $returnTags = $docBlock->getTagsByName("return");

    if (count($returnTags) > 1) {
        print "Warning: Multiple return tags." . PHP_EOL;
    }

    $returnType = $returnTags[0]->getType();
}
```

**Comment by jaapio** [comment]
Think all questions are answered here. Feel free to reopen if not
