### ISSUE TITLE
Stable release of 3.0

### ISSUE THREAD

**Issue by joelwurtz** [phpDocumentor/ReflectionDocBlock#70]
Hey,

Since this library has been mostly rewritten for 3.0, we were wondering of when do you plan to release a first stable release of this new branch ?

**Comment by fabpot** [comment]
Or put another way, is the code stable enough in terms of interfaces/names to be relied on?

**Comment by mvriel** [comment]
The API for this component hasn't changed for some time now; I'd need to check with @jaapio to be sure but if there is nothing blocking we can do a release

**Comment by fabpot** [comment]
@mvriel Thanks for the fast reply.

**Comment by mvriel** [comment]
@fabpot @joelwurtz I have just released version 3.0.0. The only thing that was really blocking was the README and I just updated that

**Comment by joelwurtz** [comment]
:heart: Thanks a lot your work on this library !

**Comment by fabpot** [comment]
\o/ Thank you!
