### ISSUE TITLE
Error installing via Composer

### ISSUE THREAD

**Issue by curtisblackwell** [phpDocumentor/ReflectionDocBlock#71]
```
phpdocumentor/reflection-docblock 3.0.0 requires phpdocumentor/reflection-common ^1.0@dev -> no matching package found.
```

There's no dev branch for [ReflectionCommon](https://github.com/phpDocumentor/ReflectionCommon).

**Comment by mvriel** [comment]
Apparently you have your composer.json set to minimum-stability 'stable'; that means that dev packages won't automatically be included. The easiest solution is to add `phpdocumentor/reflection-common ^1.0@dev` in your composer.json for now. The dev-master branch contains an alias that will facilitate this

**Comment by mvriel** [comment]
Also: I just tagged 1.0; that should also solve your issue I think :)

**Comment by curtisblackwell** [comment]
It doesn't look like I have that set, locally or globally, but tagging 1.0 worked, so I'm set. Thanks for the help!
