### ISSUE TITLE
URI not allowed in @see tag

### ISSUE THREAD

**Issue by tratajczak** [phpDocumentor/ReflectionDocBlock#78]
According to https://www.phpdoc.org/docs/latest/references/phpdoc/tags/see.html it should be possible to reference URIs but `InvalidArgumentException` is thrown. Only FQSEN are supported.

**Comment by felixfbecker** [comment]
This is causing errors in a ton of projects:

![image](https://cloud.githubusercontent.com/assets/10532611/19501881/433a3b34-95a9-11e6-9054-1f9174ee6bef.png)

**Comment by Simperfit** [comment]
@Seldaek This can be closed ?

**Comment by Seldaek** [comment]
No, the PR isn't merged yet, see https://github.com/phpDocumentor/ReflectionDocBlock/pull/88

**Comment by Christoph-Harms** [comment]
Any Info on if/when this gets merged?

**Comment by Webonaute** [comment]
I need this fix too.
