### ISSUE TITLE
% in Description is not escaped

### ISSUE THREAD

**Issue by kelunik** [phpDocumentor/ReflectionDocBlock#81]
If there are placeholders in the description, there's a PHP warning issued, because the number of arguments doesn't match. This can be solved by escaping `%` with `%` in descriptions beforehand.

Example: https://github.com/symfony/console/blob/master/Question/ChoiceQuestion.php#L108

**Comment by cebe** [comment]
In which case do you see the warning and what is the message of the warning?

**Comment by kelunik** [comment]
There's a warning about too few arguments if I create a new `DocBlock` using the factory and then render the description using `$docBlock->getDescription()->render();`. I submitted a PR.
