### ISSUE TITLE
@param $this parameter type 

### ISSUE THREAD

**Issue by ghost** [phpDocumentor/ReflectionDocBlock#85]
Hello

It seems that the `$this` parameter type is incorrectly being seen as variable name instead of type because it starts with a dollar sign:

``` php
/**
 * @param $this $someField
 */
public function foo($someField) {}
```

It is mentioned in the phpDocumentor documentation as type, which implies it should be available everywhere types are expected, but perhaps it was intentionally left out because it can be replaced by the `static` keyword or maybe it is only supported in the `@return` tag?

Thanks in advance

**Comment by cebe** [comment]
why would you pass $this via parameter? `$this` refers to exactly this instance, while `static` is object of the same type.

**Comment by Gert-dev** [comment]
That is correct, I have no practical application for it, my reason for this ticket is purely based on adherence to the documentation specification(s). In other words, seeing as `$this` can be used as type in the `@return` block, and is explicitly listed as type in the phpDocumentor documentation as well as in the BNF of the draft PSR-5, it should be usable everywhere a type is expected. If this is not desired, both documentation sources (or the one that is adhered to by this library) should mention this exception explicitly.

**Comment by felixfbecker** [comment]
Imo it should only be supported for  `@return`. `$this` is clearly defined there, it is the current object. But for `@param`, it would not be the `$this` of the method, it would be whatever `$this` is in the calling scope, which makes no sense and is undefined.

**Comment by jaapio** [comment]
I agree with @felixfbecker I don't know what it would mean if you use `$this` in a `@param`. `$this` is indeed the current object. It would be very strange to only accept the current instance. Beside that $this is not a valid type. And is only added to `@return` to be able to describe a fluent interface.
